spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dch_elearning
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/000-initial-setup.xml

app:
  jwt:
    secret: ${JWT_SECRET:zmien-mnie-na-dlugi-losowy-sekret-min-32-znaki-produkcyjnie}
    expiration-ms: 3600000

  cors:
    allowed-origins: http://localhost:3000
